### ISSUE TITLE
egress-policy: audit Is Blocking Outbound UDP 443

### ISSUE THREAD

**Issue by nibanks** [step-security/harden-runner#112]
I am having to remove this from any of my actions that makes outbound UDP 443 (QUIC) connections. When this is enabled I get no connectivity. Related: https://github.com/microsoft/msquic/pull/2534 and https://github.com/nibanks/msh3/pull/28.

**Comment by nibanks** [comment]
This effectively breaks the QUIC and HTTP/3 protocols (for which we are doing active development). So I have to remove usage of this in any jobs that are making outbound requests.

**Comment by varunsh-coder** [comment]
Thanks @nibanks for reporting. will address it ASAP.

**Comment by varunsh-coder** [comment]
@nibanks just tested out the fixed `int` version of harden-runner on fork of msh3 and msquic. 

Looks like the UDP request is going through. Can you please verify if this is what is expected? 
https://github.com/varunsh-coder/msh3/runs/5605370590?check_suite_focus=true#step:9:22
https://github.com/varunsh-coder/msquic/runs/5605545963?check_suite_focus=true#step:10:31

If this looks as expected, will continue with the release. Thanks!

**Comment by nibanks** [comment]
Yep. Both look good to me.
