### ISSUE TITLE
Trust for agent build

### ISSUE THREAD

**Issue by zwass** [step-security/harden-runner#123]
Hi, very exciting project!

I took a look at https://github.com/step-security/harden-runner/blob/main/src/checksum.ts#L13 and saw that you are verifying a checksum before installing the agent. How can I verify this checksum? I made a local build of the agent with `goreleaser` and got a different checksum for the generated `.tar.gz`.

Being able to verify the integrity of the agent binary feels like a critical step in improving the supply chain integrity.

**Comment by varunsh-coder** [comment]
Thanks @zwass!

As of now, we have not verified if the agent build is reproducible or not, and have not tried to make it reproducible. Is that what you are looking for? If so, I can create an issue in the agent repo and prioritize that. 

As of now, the release process is to release the agent, and then change the checksum in the harden-runner GitHub Action to check for the new checksum, so if the agent repo is compromised, and one changes the release, that change is detected and the harden-runner Action does not install the modified agent.

**Comment by zwass** [comment]
Yeah, I think a reproducible build would help.

The underlying problem is, how can I trust the artifacts in the release on the GitHub repo? They could have been tampered with during the CI build process and/or completely overwritten by someone with write access to the repo.

FWIW, I'm thinking about the same trust issues for our project https://github.com/fleetdm/fleet.

**Comment by varunsh-coder** [comment]
W.r.t tampering during the CI build process, that is the problem `harden-runner` is trying to solve. It currently monitors source code overwrite and outbound traffic. Do suggest improvements for detecting tampering during build that `harden-runner` can detect. 

W.r.t. overwriting release artifact in GitHub, I agree, that is a big problem, and does not get much attention. One can sign the release, but most people do not verify the signature/ checksum (e.g. in codecov breach the bash uploader was modified in the storage account, which is similar to modifying release. The codecov bash uploader checksum was available on the website, but no one was verifying it). 

One potential solution I have been thinking of is to get notified if release is modified after creation. One could implement a solution that gets a webhook on change to release, and use it to notify the owner. A more expensive solution is to poll important releases periodically to get notified on suspicious change, similar to downtime monitoring solutions. 

Happy to brainstorm other options.

**Comment by varunsh-coder** [comment]
@zwass we are starting work on a project to associate a release in GitHub with the workflow (if using GitHub Actions) and then re-build the code to see if it matches the release checksum. We plan to run this every time there is a new release by getting notified via webhook, or by polling every few hours/ minutes. If checksum does not match one can choose to get notified. 

This should take care of the two concerns you mentioned ("could have been tampered with during the CI build process and/or completely overwritten by someone with write access to the repo"). Would you like to pilot it when we get to pilot stage?

**Comment by zwass** [comment]
Yeah, I'm definitely interested. Please let me know!

**Comment by varunsh-coder** [comment]
> Yeah, I'm definitely interested. Please let me know!

Hi @zwass I was reviewing the releases for fleetdm to come up with some rules for this validation. 
e.g. if there is a new release/ update to existing release, get the workflow associated with the release. if no workflow found, notify.
I think there should also be a check around the branch from which workflow should have run.
e.g. if workflow found, check the commit against a branch. if branch is not approved (or not a protected branch?), notify. 

But when I look at the last release https://github.com/fleetdm/fleet/releases/tag/fleet-v4.13.2, I see there is a commit associated with it. But the [commit](https://github.com/fleetdm/fleet/commit/466028426bc7bb473ed76ab4493f34c81c487ce5) is not associated with a branch for some reason. Can you help me draft a good rule for your repo's release?

This is for the second threat - _release could be completely overwritten by someone with write access to the repo_. Ideally, we want the release to happen via an approved workflow from an approved branch. Else someone could create a new branch, change code in that branch, and release it via approved workflow.

**Comment by zwass** [comment]
Good question! Our major and minor version releases are almost always tagged from the `main` branch. For patch releases, we often create a patch branch, cherry-pick some commits onto that branch, and then tag from that branch. The whole process is described in https://fleetdm.com/docs/contributing/releasing-fleet#patch-releases. We often delete the patch branch when we are done, leaving just the tag in the repo.

**Comment by varunsh-coder** [comment]
> Good question! Our major and minor version releases are almost always tagged from the `main` branch. For patch releases, we often create a patch branch, cherry-pick some commits onto that branch, and then tag from that branch. The whole process is described in https://fleetdm.com/docs/contributing/releasing-fleet#patch-releases. We often delete the patch branch when we are done, leaving just the tag in the repo.

thanks for the info! I am looking into this.

**Comment by varunsh-coder** [comment]
Hi @zwass, we are building a GitHub App tentatively called "Release Monitor". It will need `contents: read` and `actions: read` and will setup a webhook for [releases](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release). When there is a new release/ change to a release, it will correlate the release with the expected workflow (`goreleaser-fleet.yaml` in your case) and branch (`main` for major/ minor versions). 

If release is via unexpected workflow, it will notify via email. In future version, it will correlate workflow to branch, and if it is from unexpected branch, will notify via email. We should have a beta version in a week or so. 

Looking forward for you to pilot it. Please let me know if this plan sounds good, or if you have any feedback. We need to figure out how/ where to specify the expected release workflow (`expected release workflow as code`, may be). We will just hardcode it for you to start with and can evolve it over time. 

Also, is it ok if I convert this issue into a discussion? 

/cc @h0x0er

**Comment by zwass** [comment]
Please feel free to convert/modify this issue as you like.

I'm interested in what you are describing, but my top priority would be seeing a reproducible build of the `harden-runner` agent so that I can feel good about installing it before the build in my release action (and our users can verify that the `harden-runner` agent that ran during the build was indeed the expected one).

**Comment by varunsh-coder** [comment]
> Please feel free to convert/modify this issue as you like.
> 
> I'm interested in what you are describing, but my top priority would be seeing a reproducible build of the `harden-runner` agent so that I can feel good about installing it before the build in my release action (and our users can verify that the `harden-runner` agent that ran during the build was indeed the expected one).

@zwass I will prioritize reproducible build of the `harden-runner` agent and keep this issue open until then. 

I do want to clarify that `release-monitor` (new project) has different set of features to address different threats from `harden-runner`. You don't need to add `harden-runner` in your release workflow to get benefit of `release-monitor`.

The `release monitor` App will tell you if your GitHub release was modified/ released via the GitHub API without proper process by someone with write access. `harden-runner` would not have helped with that anyways. 

`release monitor` will also re-build fleet in a separate environment for the same commit and compare checksum, and will notify you if they don't match. This is again something that needs to be done separately from `harden-runner`.

I need to do these two things for `harden-runner` agent as well, and once those are done, you can add it to your workflows to detect compromised build tools/ dependencies.

Hope that clarifies.

**Comment by varunsh-coder** [comment]
step-security/agent build is now reproducible! Thanks for pushing to get this done!

This is the URL to check the reproduced build: https://app.stepsecurity.io/github/step-security/agent/releases/latest

`harden-runner` has not been updated to use the latest `agent` version yet. Will do that soon.

**Comment by varunsh-coder** [comment]
Released the latest version of `harden-runner` that uses agent with reproducible build. Also added information to the README to view steps to reproduce build for agent. 

I will go ahead and close this issue. Feel free to re-open in case I missed something. Thanks!
