### ISSUE TITLE
Protecting link in private repositories

### ISSUE THREAD

**Issue by jurasofish** [step-security/harden-runner#130]
This tool looks really great, keen to give it a try.

I'm thinking of using it in a private repo. It seems that if I do that then the generated URL will be public and it will follow the predictable pattern of `{org}/{repo}/actions/runs/{runid}`. Is that right?

I understand I can disable sending telemetry to the step security API which will ensure the details aren't made public - but in that case it seems there's no practical way of doing an initial workflow run to determine which endpoints etc. to whitelist (e.g. with egress-policy: audit)

- Is there any way to have the report that's hosted on app.stepsecurity.io generated as a static file and saved as a workflow artefact?
- Is there any way to have the report URL contain, say, a secret string? A random URL so it's not guessable, but is still publicly accessible?
- do you have other plans for handing this issue?

**Comment by varunsh-coder** [comment]
Hi @jurasofish, thanks for reaching out!

If you use it for a private repo, the generated URL is NOT public. It follows the pattern, but only those who have access to the repo can view it. You need to authenticate first to access it for private repo. 

This is an example of a non-sensitive private repo in step-security org. You can try it out to see the experience. You will get a forbidden error message: https://app.stepsecurity.io/github/step-security/harden-runner-repro/actions/runs/2236232495

The API knows if the repo is private and limits access only to those who have access to the repo. You will need to install [Harden-Runner App](https://github.com/marketplace/harden-runner-app) to use it for Private repo. It only needs `actions: read` permission to download build logs. The App is also used to authenticate the user to check for access to the repo. 

W.r.t saving the report as workflow artifact, we can certainly look into that. 

Please let me know if you have any other questions/ concerns! Happy to address and looking forward to you trying it out!

**Comment by jurasofish** [comment]
Ah that's great - I should have just given it a try sorry! Thanks for such a quick response. Saving as a workflow artefact would definitely be nice, but not at all critical imo given that the private repo reports are not public.
