### ISSUE TITLE
Limit annotations for source code overwrite

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#137]
Limit the number of annotations created for source code overwrite. They should be enough to know there is an issue, but should not clutter up the action results. Plan is to allow 3 annotations per exe that is overwriting source files per job.

**Comment by ben-manes** [comment]
A sarif report and uploading to GitHub security dashboard would be a nice touch for visibility and easy suppression

**Comment by varunsh-coder** [comment]
> A sarif report and uploading to GitHub security dashboard would be a nice touch for visibility and easy suppression

Created an issue to track it. Thanks!
