### ISSUE TITLE
Insights not generated for osfanbuff63/discord-bot

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#158]
Insights were not being generated for one of the workflows in osfanbuff63/discord-bot : https://github.com/osfanbuff63/discord-bot/blob/master/.github/workflows/ci.yml

The issue has been resolved now. Insights URL for latest run:
https://app.stepsecurity.io/github/osfanbuff63/discord-bot/actions/runs/2840505125

@osfanbuff63 - FYI, I observed insights were not being generated for one of your workflows. Have resolved the bug. Should work for future workflow runs.

**Comment by varunsh-coder** [comment]
Closing issue. Feel free to re-open if you see this issue again.

**Comment by osfanbuff63** [comment]
Thanks! I saw that reports hadn't been generated yet, but it was right after the workflow ran and decided to wait, and then I forgot about it so I never thought to report it :P

**Comment by varunsh-coder** [comment]
No problem. Please let me know if you have any suggestions for improving `harden-runner`. Thanks!
