### ISSUE TITLE
Harden runner log showing warnings instead of normal logs

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#161]
I noticed here that normal logs are being shown as warnings:
https://github.com/miguelnietoa/stellar_sdk/runs/7881603461?check_suite_focus=true#step:20:4

This does not happen typically and I cannot find it for other runs. Here is a typical run: https://github.com/harden-runner-canary/dassana/runs/7880455490?check_suite_focus=true#step:12:4

@miguelnietoa thanks for using `harden-runner`! Do you have a configuration in your workflow that treats some kind of logs as warnings? I am trying to investigate why normal `harden-runner` logs are showing as warnings for your workflow run. If not, I will investigate further. Thanks!

**Comment by varunsh-coder** [comment]
@h0x0er can you please investigate this?

**Comment by miguelnietoa** [comment]
Hi @varunsh-coder  👋
I was investigating why this happens but have not yet found out why. I just have to say that this happens with this repository for the CI(test)/CD(publish) workflows, but not for the scorecards' workflow.

Scorecards' workflow URL: https://github.com/miguelnietoa/stellar_sdk/runs/7892093970?check_suite_focus=true ✅ 

---
I was trying it out in another repo and the logs are shown as normal, not as warnings.
https://github.com/miguelnietoa/editorjs-toggle-block/actions/runs/2878646179

**Comment by varunsh-coder** [comment]
Thanks for the info!

**Comment by h0x0er** [comment]
@varunsh-coder I continued my investigation and found that the `warnings` are occurring because of `elixir`. I am still unable to figure the root cause..
 
Checkout:
https://github.com/h0x0er/stellar_sdk/actions
https://github.com/h0x0er/elixir-warning-investigation/actions/runs/2901181399

**Comment by varunsh-coder** [comment]
I think it has to do with `problem_matchers`. Try to find out more about them. 
https://github.com/erlef/setup-beam/blob/69fb25ba7e2c546dfc085871ecf2fc5382c9843d/src/setup-beam.js#L79

If you set `disable_problem_matchers ` to true, see if the issue goes away?

**Comment by h0x0er** [comment]
@varunsh-coder It worked !!

**Comment by varunsh-coder** [comment]
So we need to understand how to disable problem_matchers when post harden-runner step starts. Or may be there is a bug in the way they have enabled it, so the action owners need to fix it on their side?

**Comment by varunsh-coder** [comment]
Hi @miguelnietoa, I noticed that you added a wildcard to the allowed endpoint for Azure storage. 
https://github.com/kommitters/editorjs-toggle-block/commit/d69e475439f02ac85eb47ac1311e6e66cb74daf9

`harden-runner` does not support wildcards in domain names. As a result, harden-runner is not working for these two workflows. 

You can see this in the log here:
https://github.com/kommitters/editorjs-toggle-block/runs/8138266022?check_suite_focus=true#step:14:21

Can you please tell me why you wanted to use wildcard domain? The fixed domain you had earlier seemed to be working fine.   That endpoint is needed for cache and should be specific to your repo's workflows. Would be great if you can use the earlier fixed endpoint. Thanks!

**Comment by miguelnietoa** [comment]
Hi @varunsh-coder, thanks a lot!! ✨

I used wildcard domain to make it work for forks as well. But I will change it to the earlier fixed endpoint understanding this is repo specific. Thanks again. 💯

**Comment by varunsh-coder** [comment]
Thanks @miguelnietoa! We are working on a change where in the future harden-runner will automatically detect the cache endpoint. So then it will work fine on forks as well and will not need to be explicitly added to the allowed list. But until then whoever forks the repo will need to update the endpoint.

**Comment by varunsh-coder** [comment]
Hi @miguelnietoa, 

I forgot to update you on the original issue. The reason the `harden-runner` logs were showing as warnings is because `erlef/setup-beam` (erlef/setup-elixir has been renamed I believe to erlef/setup-beam) GitHub Action adds problem_matchers. These are regular expressions and they were matching the timestamp added to `harden-runner` logs. 

@h0x0er had also created an [issue](https://github.com/erlef/setup-beam/issues/136) to discuss it. 

There is nothing much we can do about this. If you do not need the warnings from erlef/setup-beam Action, you can set `disable_problem_matchers` to `true`. That will solve the problem. 

Please let me know if you have any follow up questions...

**Comment by miguelnietoa** [comment]
> Hi @miguelnietoa,
> 
> I forgot to update you on the original issue. The reason the `harden-runner` logs were showing as warnings is because `erlef/setup-beam` (erlef/setup-elixir has been renamed I believe to erlef/setup-beam) GitHub Action adds problem_matchers. These are regular expressions and they were matching the timestamp added to `harden-runner` logs.
> 
> @h0x0er had also created an [issue](https://github.com/erlef/setup-beam/issues/136) to discuss it.
> 
> There is nothing much we can do about this. If you do not need the warnings from erlef/setup-beam Action, you can set `disable_problem_matchers` to `true`. That will solve the problem.
> 
> Please let me know if you have any follow up questions...


I have no further questions and leave it to your consideration whether this issue should be closed as it is outside the scope of harden-runner action.

Thanks for the research on this and bringing me up to speed!  @varunsh-coder @h0x0er 😄 💯

**Comment by varunsh-coder** [comment]
Thanks @miguelnietoa! I will go ahead and close the issue.
