### ISSUE TITLE
Insights not generated for `raphw/byte-buddy`

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#167]
Insights were not being generated for `raphw/byte-buddy`. 

On investigation it was found a change released to the Insights API yesterday had caused this. The change has been reverted for now and insights are being generated now. 

@raphw tagging you in this issue. Sorry about the inconvenience. The issue is resolved now. Please review the insights and let me know if you have any questions. Thanks for using `harden-runner`!

Here are some of the insights links:
https://app.stepsecurity.io/github/raphw/byte-buddy/actions/runs/2903420769
https://app.stepsecurity.io/github/raphw/byte-buddy/actions/runs/2904914749

Feel free to create an issue in this repo if you have any issues.

**Comment by varunsh-coder** [comment]
While this issue was caused due to a bug, in general, the insights are generated faster if you install this [App](https://github.com/marketplace/harden-runner-app). It uses an App specific token to download the build logs, so requests to the GitHub API are not throttled.

**Comment by varunsh-coder** [comment]
Hi @raphw, I saw that you added the `allowed-endpoints` for one of the jobs. 

I noticed that one of the endpoints is not accurate, and as a result `harden-runner` is not able to resolve the domain name. When that happens, it reverts the policy and does not block traffic. 

`blob.core.windows.net:443`

Can you please use the specific subdomain instead? This will remain same for your repository. There were also couple of endpoints missing. Here is what the final list should be:

``` yaml
- name: Harden Runner
  uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
  with:
    egress-policy: block
    allowed-endpoints: >
      artifactcache.actions.githubusercontent.com:443
      aw97acprodeus1file2.blob.core.windows.net:443
      coveralls.io:443
      docs.gradle.org:443
      docs.oracle.com:443
      downloads.gradle-dn.com:443
      github.com:443
      javadoc.io:443
      plugins.gradle.org:443
      plugins-artifacts.gradle.org:443
      raw.githubusercontent.com:443
      repo.gradle.org:443
      repo.maven.apache.org:443
      services.gradle.org:443

```

**Comment by vigasdeep** [comment]
@varunsh-coder hey! is this still an issue? seems like a pretty old issue, I was thinking to pick some up.

**Comment by raphw** [comment]
I missed this ticket back in the days but adjusted the file now.

**Comment by varunsh-coder** [comment]
@raphw I did more analysis and looks like the endpoints needed to be updated. I have created a PR for this: https://github.com/raphw/byte-buddy/pull/1671. Please let me know if you have any questions. 

@vigasdeep thanks for reviving the thread and helping to get this resolved!

**Comment by vigasdeep** [comment]
@varunsh-coder Awesome, are there any good first issues there? I'm really interested in contributing.

**Comment by varunsh-coder** [comment]
> raphw/byte-buddy#1671

@vigasdeep I will keep an eye out for good first issues and will tag you. 

Closing this issue. Thanks!
