### ISSUE TITLE
Docker build fails with update to 2.2.0

### ISSUE THREAD

**Issue by jmgrady** [step-security/harden-runner#250]
Our docker builds now fail with the update to 2.2.0.  The GitHub Action log is at https://github.com/sillsdev/TheCombine/actions/runs/4234817715

Notice in particular the build for the maintenance component (it was the first failure and canceled the others).  The logs state:

```
The command '/bin/sh -c apt-get update &&   apt-get install -y python3 python3-pip nano &&   apt-get autoremove &&   apt-get clean &&   rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Error: Process completed with exit code 100.
```

I believe this is due to what was logged in the Post Harden Runner section:

```
Error: StepSecurity Harden Runner: Traffic to IP Address 185.125.190.36 was blocked
Error: StepSecurity Harden Runner: Traffic to IP Address 91.189.91.39 was blocked
```

However, the endpoints were set to match what was recommended (this is a super-set to cover all 4 builds):

```
          allowed-endpoints: >
            ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
            api.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com:443
            sts.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com:443
            api.github.com:443
            api.nuget.org:443
            archive.ubuntu.com:443
            auth.docker.io:443
            codecov.io:443
            dc.services.visualstudio.com:443
            deb.debian.org:443
            docker.io:443
            dotnetcli.azureedge.net:443
            files.pythonhosted.org:443
            github.com:443
            pipelines.actions.githubusercontent.com:443
            production.cloudflare.docker.com:443
            pypi.org:443
            registry.npmjs.org:443
            registry-1.docker.io:443
            security.debian.org:443
            security.ubuntu.com:443
            storage.googleapis.com:443
            uploader.codecov.io:443
```

**Comment by jmgrady** [comment]
Note that according to a previous build that was successful:
```
Wed, 22 Feb 2023 14:21:07 GMT:domain resolved: archive.ubuntu.com., ip address: 185.125.190.36, TTL: 30
Wed, 22 Feb 2023 14:21:07 GMT:domain resolved: security.ubuntu.com., ip address: 91.189.91.39, TTL: 30
```

It appears that traffic is being blocked to allowed endpoints.

**Comment by varunsh-coder** [comment]
Hi @jmgrady I believe this is because the calls are being made to port `80`, but the allowed endpoints only mention port `443`. 

If you see the insights [link](https://app.stepsecurity.io/github/sillsdev/TheCombine/actions/runs/4234817715), it has these details (screenshot)

<img width="820" alt="Screen Shot 2023-02-22 at 7 32 21 AM" src="https://user-images.githubusercontent.com/25015917/220671850-16e9ac3f-8d09-493c-8b13-021e7ba67f7a.png">

Can you please add these two allowed endpoints? 
`archive.ubuntu.com:80`
`security.ubuntu.com:80`

**Comment by jmgrady** [comment]
That fixes the problem.  Thank you for your help.
