### ISSUE TITLE
Logo in build summary is not readable on the Dark Theme

### ISSUE THREAD

**Issue by rajbos** [step-security/harden-runner#275]
"Harden runner" is black, doesn't work that well 😄.

![image](https://user-images.githubusercontent.com/6085745/231858441-2ed22c2b-fe6b-47bd-9119-91b0a84f8416.png)

**Comment by varunsh-coder** [comment]
Thanks for reporting this issue @rajbos! I will get it addressed soon.

**Comment by varunsh-coder** [comment]
I got the new logo for dark theme. I will add it to this issue. 

This is how we can use for different themes
https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/

We need to update the README and here
https://github.com/step-security/harden-runner/blob/910b3276b25495e4cfd8669cf5d7ea16508b0241/src/common.ts#L19

@arjundashrath please take this up.

**Comment by varunsh-coder** [comment]
![HardenRunnerDarkTheme](https://user-images.githubusercontent.com/25015917/232882291-2b9b3a32-166b-4a50-8bb6-d8c30cd3e301.png)
I am attaching the dark theme logo.

**Comment by varunsh-coder** [comment]
@rajbos, this is fixed and released. Please let me know if you still see an issue. Thanks!
