### ISSUE TITLE
Consider adding simple checksum validation for the downloaded tar prior to extraction / execution

### ISSUE THREAD

**Issue by chetanbhat** [step-security/harden-runner#54]
https://github.com/step-security/harden-runner/blob/0045e636d87a56c1dca21729e8cfc97d6d994de5/src/setup.ts#L57

**Comment by varunsh-coder** [comment]
@h0x0er can you please take this up? Have a look at [this](https://github.com/gradle/wrapper-validation-action/tree/master/src) code or look for other implementations.

**Comment by h0x0er** [comment]
Thanks @varunsh-coder for assigning the issue. 
Sure, i can handle this issue.
