### ISSUE TITLE
Investigate run

### ISSUE THREAD

**Issue by varunsh-coder** [step-security/harden-runner#71]
https://github.com/MTRNord/matrix-art/actions/runs/1743376122

**Comment by varunsh-coder** [comment]
Hi @MTRNord, I observed that one of the runs failed due to harden-runner. We will investigate.

Do let me know if you have feedback to improve `harden-runner` or https://app.stepsecurity.io, specially around developer experience. Thanks!

**Comment by h0x0er** [comment]
@varunsh-coder I will investigate this issue.

**Comment by varunsh-coder** [comment]
Observed another similar issue: https://github.com/jauderho/dockerfiles/actions/runs/1883469545

**Comment by varunsh-coder** [comment]
Such instances have not been seen in several months and should have been fixed due to improvements made. Closing issue.
