### ISSUE TITLE
Formatting bug with latest harden runner ouput

### ISSUE THREAD

**Issue by jauderho** [step-security/harden-runner#88]
When copying the latest code block output from https://app.stepsecurity.io/github/jauderho/dockerfiles/actions/runs/1800983360 , I notice an issue. There seems to be a spurious `>` in the code block in the same line as `allowed-endpoints:`. 

See below for example,

```
- name: Harden Runner
  uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
  with:
    egress-policy: block
    allowed-endpoints: >
      95s5acprodeus1file6.blob.core.windows.net:443
      api.github.com:443
      artifactcache.actions.githubusercontent.com:443
      crates.io:443
      dl-cdn.alpinelinux.org:443
      ghcr.io:443
      github.com:443
      production.cloudflare.docker.com:443
      registry-1.docker.io:443
      sh.rustup.rs:443
      static.crates.io:443
      static.rust-lang.org:443
```

**Comment by varunsh-coder** [comment]
Hi @jauderho thanks for creating the issue. This change was made to address #82. Basically, the earlier formatting was getting changed when one used VS Code. The `>` sign is a standard method to format YAML. Please let me know if you have feedback. Thanks!

**Comment by varunsh-coder** [comment]
@jauderho I will go ahead and close this based on the comments above. Feel free to comment if you have ideas to improve it...Thanks!
